### PR TITLE
Issue #12: Remove unzip dependency

### PR DESCRIPTION
**Pull request by gavinwade12**
Addresses issue #12

### CODE REVIEW

**Comment by mstruebing** [comment]
Argh, I'll go to sleep now. :)
I wanted to do it myself tomorrow morning that's why I've assigned myself to that issue.
Thanks anyways but let some stuff for me to do ;)

But honestly, great work I appreciate that.

**Comment by gavinwade12** [comment]
Sorry, I just wanted to knock a quick one out lol. You can take over this one from here and change anything if you'd like. I'll tackle a different issue next time I get some free time.

**Comment by mstruebing** [comment]
Don't worry, I'm happy to have an active contributor, will review tomorrow

**Comment by mstruebing** [comment]
Is working fine

**Pull request merged**
